# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN
        ROLE_SUPER_SUPER_ADMIN: ROLE_SUPER_ADMIN



    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                # if you are using Symfony < 2.8, use the following config instead:
                #csrf_provider: form.csrf_provider

            logout:       true
            anonymous:    true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, role: ROLE_USER }
        - { path: ^/cursos, role: ROLE_USER }
        - { path: ^/docentes, role: ROLE_USER }
        - { path: ^/comisiones, role: ROLE_USER }
        - { path: ^/alumnos, role: ROLE_USER }
        - { path: ^/parcial, role: ROLE_USER }
        - { path: ^/clase, role: ROLE_USER }
        - { path: ^/instanciaparcial, role: ROLE_USER }
        - { path: ^/catedras, role: ROLE_SUPER_SUPER_ADMIN }
        - { path: ^/reporteAsistencia, role: ROLE_USER }
        - { path: ^/user, role: ROLE_USER }
        - { path: ^/asistencias, role: ROLE_USER }
        - { path: ^/notas, role: ROLE_USER }
        - { path: ^/reporteNotas, role: ROLE_USER }
        - { path: ^/reporteAlumno, role: ROLE_USER }