<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Alumnos extends \AppBundle\Entity\Alumnos implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Alumnos' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Alumnos' . "\0" . 'password', '' . "\0" . 'AppBundle\\Entity\\Alumnos' . "\0" . 'apellido', '' . "\0" . 'AppBundle\\Entity\\Alumnos' . "\0" . 'nombre', '' . "\0" . 'AppBundle\\Entity\\Alumnos' . "\0" . 'dni', '' . "\0" . 'AppBundle\\Entity\\Alumnos' . "\0" . 'legajo', '' . "\0" . 'AppBundle\\Entity\\Alumnos' . "\0" . 'origen', '' . "\0" . 'AppBundle\\Entity\\Alumnos' . "\0" . 'telefono', '' . "\0" . 'AppBundle\\Entity\\Alumnos' . "\0" . 'celular', '' . "\0" . 'AppBundle\\Entity\\Alumnos' . "\0" . 'mail', 'clases', 'instanciasParciales');
        }

        return array('__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Alumnos' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Alumnos' . "\0" . 'password', '' . "\0" . 'AppBundle\\Entity\\Alumnos' . "\0" . 'apellido', '' . "\0" . 'AppBundle\\Entity\\Alumnos' . "\0" . 'nombre', '' . "\0" . 'AppBundle\\Entity\\Alumnos' . "\0" . 'dni', '' . "\0" . 'AppBundle\\Entity\\Alumnos' . "\0" . 'legajo', '' . "\0" . 'AppBundle\\Entity\\Alumnos' . "\0" . 'origen', '' . "\0" . 'AppBundle\\Entity\\Alumnos' . "\0" . 'telefono', '' . "\0" . 'AppBundle\\Entity\\Alumnos' . "\0" . 'celular', '' . "\0" . 'AppBundle\\Entity\\Alumnos' . "\0" . 'mail', 'clases', 'instanciasParciales');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Alumnos $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setPassword($password)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPassword', array($password));

        return parent::setPassword($password);
    }

    /**
     * {@inheritDoc}
     */
    public function getPassword()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPassword', array());

        return parent::getPassword();
    }

    /**
     * {@inheritDoc}
     */
    public function setApellido($apellido)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setApellido', array($apellido));

        return parent::setApellido($apellido);
    }

    /**
     * {@inheritDoc}
     */
    public function getApellido()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getApellido', array());

        return parent::getApellido();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombre($nombre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombre', array($nombre));

        return parent::setNombre($nombre);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombre', array());

        return parent::getNombre();
    }

    /**
     * {@inheritDoc}
     */
    public function setDni($dni)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDni', array($dni));

        return parent::setDni($dni);
    }

    /**
     * {@inheritDoc}
     */
    public function getDni()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDni', array());

        return parent::getDni();
    }

    /**
     * {@inheritDoc}
     */
    public function setLegajo($legajo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLegajo', array($legajo));

        return parent::setLegajo($legajo);
    }

    /**
     * {@inheritDoc}
     */
    public function getLegajo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLegajo', array());

        return parent::getLegajo();
    }

    /**
     * {@inheritDoc}
     */
    public function setOrigen($origen)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOrigen', array($origen));

        return parent::setOrigen($origen);
    }

    /**
     * {@inheritDoc}
     */
    public function getOrigen()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrigen', array());

        return parent::getOrigen();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelefono($telefono)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelefono', array($telefono));

        return parent::setTelefono($telefono);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelefono()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelefono', array());

        return parent::getTelefono();
    }

    /**
     * {@inheritDoc}
     */
    public function setCelular($celular)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCelular', array($celular));

        return parent::setCelular($celular);
    }

    /**
     * {@inheritDoc}
     */
    public function getCelular()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCelular', array());

        return parent::getCelular();
    }

    /**
     * {@inheritDoc}
     */
    public function setMail($mail)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMail', array($mail));

        return parent::setMail($mail);
    }

    /**
     * {@inheritDoc}
     */
    public function getMail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMail', array());

        return parent::getMail();
    }

    /**
     * {@inheritDoc}
     */
    public function addClase(\AppBundle\Entity\AlumnoClase $clases)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addClase', array($clases));

        return parent::addClase($clases);
    }

    /**
     * {@inheritDoc}
     */
    public function removeClase(\AppBundle\Entity\AlumnoClase $clases)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeClase', array($clases));

        return parent::removeClase($clases);
    }

    /**
     * {@inheritDoc}
     */
    public function getClases()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClases', array());

        return parent::getClases();
    }

    /**
     * {@inheritDoc}
     */
    public function addInstanciasParciale(\AppBundle\Entity\AlumnosParcial $instanciasParciales)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addInstanciasParciale', array($instanciasParciales));

        return parent::addInstanciasParciale($instanciasParciales);
    }

    /**
     * {@inheritDoc}
     */
    public function removeInstanciasParciale(\AppBundle\Entity\AlumnosParcial $instanciasParciales)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeInstanciasParciale', array($instanciasParciales));

        return parent::removeInstanciasParciale($instanciasParciales);
    }

    /**
     * {@inheritDoc}
     */
    public function getInstanciasParciales()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInstanciasParciales', array());

        return parent::getInstanciasParciales();
    }

}
